const templates = require('../template_pages');

const options_list = [{
    feed_title: '全国季报',
    feed_desc: '全国季报',
    feed_image: 'http://www.mca.gov.cn/images/logo.png',
    feed_url: 'http://www.mca.gov.cn/article/sj/tjjb/qgsj/',
    url: 'http://www.mca.gov.cn/article/sj/tjjb/qgsj/',
    baseUrl: 'http://www.mca.gov.cn',
    list_slr: ['tr', 'table.article tbody'],
    title_slr: 'a.artitlelist',
    link_slr: 'a.artitlelist',
    link_rel: true,
    desc_slr: 'a.artitlelist',
    time_slr: 'td.timedefault',
    cn: false,
},
{
    feed_title: '省级季报',
    feed_desc: '省级季报',
    feed_image: 'http://www.mca.gov.cn/images/logo.png',
    feed_url: 'http://www.mca.gov.cn/article/sj/tjjb/sjsj/',
    url: 'http://www.mca.gov.cn/article/sj/tjjb/sjsj/',
    baseUrl: 'http://www.mca.gov.cn',
    list_slr: ['tr', 'table.article tbody'],
    title_slr: 'a.artitlelist',
    link_slr: 'a.artitlelist',
    link_rel: true,
    desc_slr: 'a.artitlelist',
    time_slr: 'td.timedefault',
    cn: false,
},
{
    feed_title: '全国月报',
    feed_desc: '全国月报',
    feed_image: 'http://www.mca.gov.cn/images/logo.png',
    feed_url: 'http://www.mca.gov.cn/article/sj/tjyb/qgsj/',
    url: 'http://www.mca.gov.cn/article/sj/tjyb/qgsj/',
    baseUrl: 'http://www.mca.gov.cn',
    list_slr: ['tr', 'table.article tbody'],
    title_slr: 'a.artitlelist',
    link_slr: 'a.artitlelist',
    link_rel: true,
    desc_slr: 'a.artitlelist',
    time_slr: 'td.timedefault',
    cn: false,
},
{
    feed_title: '省级月报',
    feed_desc: '省级月报',
    feed_image: 'http://www.mca.gov.cn/images/logo.png',
    feed_url: 'http://www.mca.gov.cn/article/sj/tjyb/sjsj/',
    url: 'http://www.mca.gov.cn/article/sj/tjyb/sjsj/',
    baseUrl: 'http://www.mca.gov.cn',
    list_slr: ['tr', 'table.article tbody'],
    title_slr: 'a.artitlelist',
    link_slr: 'a.artitlelist',
    link_rel: true,
    desc_slr: 'a.artitlelist',
    time_slr: 'td.timedefault',
    cn: false,
}];

module.exports = templates({
    title: '民政部-统计',
    link: 'http://www.mca.gov.cn/article/sj/tjjb/qgsj/',
    image: 'http://www.mca.gov.cn/images/logo.png',
    description: '民政部-统计',
    options_list
});
